modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="iron_man"
version="1.0.0"
displayName="Iron Man"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="allan, MCreator"

[[dependencies.iron_man]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



